services:
  - type: web
    name: telegram-mini-app
    env: static
    buildCommand: ""
    startCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600